project:
  type: website
  output-dir: docs

website:
  title: "Brandon's Quarto Website"
  navbar:
    background: primary
    search: true
    left:
      - href: index.qmd
        text: Homepage
      - about.qmd
    right:
      - icon: github
        href: https://github.com/SloppyBobbert/385_website
  sidebar:
    style: "docked"
    search: true
    contents:
      - section: "Assignments"
        contents:
           - ae05-git-together.qmd
format:
  html:
    theme:
      light: lux
      dark: slate
    css: styles.css
    toc: true

editor: visual

